#ifndef ACTIONS_ENUMS
#define ACTIONS_ENUMS

#include <QString>
#include <QMap>


//! @brief
enum OUTGOING_ACTIONS_NAMES {
    DELETE_FRIEND,
    SEND_FRIEND_REQUEST,
    SEND_GAME_INVITE,
    SUBSCRIBE
};

//! @brief
enum INCOMING_ACTIONS_NAMES {
    GAME_INVITE_SENT,
    INCOMIG_GAME_INVITE,
    DELETED_BY_FRIEND,
    FRIEND_DELETED,
    NEW_FRIEND_REQUEST,
    FRIEND_REQUEST_PROCESSED,
    SUBSCRIBED
};

//! @brief
const QMap<INCOMING_ACTIONS_NAMES, QString> INCOMING_ACTIONS = {
    {INCOMING_ACTIONS_NAMES::GAME_INVITE_SENT, "game_invite_sent"},
    {INCOMING_ACTIONS_NAMES::INCOMIG_GAME_INVITE, "incoming_game_invite"},
    {INCOMING_ACTIONS_NAMES::DELETED_BY_FRIEND, "deleted_by_friend"},
    {INCOMING_ACTIONS_NAMES::FRIEND_DELETED, "friend_deleted"},
    {INCOMING_ACTIONS_NAMES::NEW_FRIEND_REQUEST, "new_friend_request"},
    {INCOMING_ACTIONS_NAMES::FRIEND_REQUEST_PROCESSED, "friend_request_processed"},
    {INCOMING_ACTIONS_NAMES::SUBSCRIBED, "subscribed"}
};

//! @brief
const QMap<OUTGOING_ACTIONS_NAMES, QString> OUTGOING_ACTIONS = {
    {OUTGOING_ACTIONS_NAMES::DELETE_FRIEND, "delete_friend"},
    {OUTGOING_ACTIONS_NAMES::SEND_FRIEND_REQUEST, "send_friend_request"},
    {OUTGOING_ACTIONS_NAMES::SEND_GAME_INVITE, "send_game_invite"},
    {OUTGOING_ACTIONS_NAMES::SUBSCRIBE, "subscribe"}
};
#endif // ACTIONS_ENUMS
