# Generated by Django 5.0.3 on 2024-04-24 08:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=30, unique=True)),
                ('user_id_turn', models.IntegerField(unique=True)),
                ('game_is_over', models.BooleanField(default=False)),
                ('winner_id', models.IntegerField(null=True)),
                ('is_friendly', models.BooleanField(default=False)),
                ('game_invite_id', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('user_password', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)])),
                ('user_id', models.IntegerField(unique=True)),
                ('user_email', models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.EmailValidator()])),
                ('silver_coins', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('win_streak', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type_name', models.CharField(choices=[('Самолёт', 'Airplane'), ('Ядерная бомба', 'Nuke Bomb'), ('Бомба', 'Small Bomb'), ('Торпеда', 'Tin Fish')], max_length=30, unique=True)),
                ('weapon_x_range', models.IntegerField()),
                ('weapon_y_range', models.IntegerField()),
                ('weapon_price', models.FloatField(default=0.0)),
                ('massive_damage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_deck', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('two_deck', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('three_deck', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('four_deck', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldChild', to='RestfulRequests.game')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RestfulRequests.user')),
            ],
        ),
        migrations.CreateModel(
            name='MissedCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulRequests.field')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_length', models.IntegerField()),
                ('is_dead', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulRequests.field')),
            ],
            options={
                'verbose_name': 'Ship',
                'verbose_name_plural': 'Ships',
            },
        ),
        migrations.CreateModel(
            name='ShipPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('is_damaged', models.BooleanField(default=False)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulRequests.ship')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_friend', to='RestfulRequests.user')),
                ('second_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_friend', to='RestfulRequests.user')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='RestfulRequests.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='RestfulRequests.user')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_amount', models.IntegerField(default=0)),
                ('weapon_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulRequests.user')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestfulRequests.weapontype')),
            ],
        ),
    ]
