# Generated by Django 5.0.4 on 2024-04-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldChild', to='RestfulRequests.game'),
        ),
    ]
