# Generated by Django 5.0.4 on 2024-04-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0003_alter_weapontype_weapon_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_infinite',
            field=models.BooleanField(default=False),
        ),
    ]
