# Generated by Django 5.0.4 on 2024-04-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0005_remove_weapon_is_infinite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_id_turn',
            field=models.IntegerField(unique=True),
        ),
    ]
