# Generated by Django 5.0.4 on 2024-04-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0006_alter_game_user_id_turn'),
    ]

    # operations = [
    #     migrations.RenameModel(
    #         old_name='MarkedCell',
    #         new_name='MissedCell',
    #     ),
    # ]
