# Generated by Django 5.0.4 on 2024-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0007_rename_markedcell_missedcell'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_id',
            field=models.IntegerField(default=None),
        ),
    ]
