# Generated by Django 5.0.4 on 2024-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0008_game_winner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
