# Generated by Django 5.0.4 on 2024-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0009_alter_game_winner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner_id',
            field=models.IntegerField(null=True),
        ),
    ]
