# Generated by Django 5.0.4 on 2024-04-23 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0011_remove_game_has_winner_alter_field_four_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='silver_coins',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
