# Generated by Django 5.0.4 on 2024-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0012_user_silver_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent_is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='weapon_type_name',
            field=models.CharField(choices=[('Самолёт', 'Airplane'), ('Ядерная бомба', 'Nuke Bomb'), ('Бомба', 'Small Bomb'), ('Торпеда', 'Tin Fish')], max_length=30, unique=True),
        ),
    ]
