# Generated by Django 5.0.4 on 2024-04-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0013_game_opponent_is_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
