# Generated by Django 5.0.4 on 2024-04-30 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0014_user_is_temporary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(4)])),
                ('min_cups_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_cups_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cups',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
