# Generated by Django 5.0.6 on 2024-05-11 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0017_alter_game_game_invite_id_alter_game_winner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_invite_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_is_over',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_friendly',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_is_ai',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='massive_damage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='weapon_price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
