# Generated by Django 5.0.6 on 2024-05-11 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestfulRequests', '0018_alter_game_game_invite_id_alter_game_game_is_over_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerleague',
            name='league_name',
            field=models.CharField(choices=[('Бронзовая лига', 'Bronze League'), ('Серебряная лига', 'Silver League'), ('Золотая лига', 'Golden League'), ('Алмазная лига', 'Diamond League')], max_length=15, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
