# Generated by Django 5.0.1 on 2024-02-04 19:20

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=30)),
                ('user_id_turn', models.CharField(max_length=30)),
                ('game_is_over', models.BooleanField(default=False)),
                ('has_winner', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('user_password', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)])),
                ('user_id', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(30)])),
                ('user_email', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type_name', models.CharField(choices=[('Самолёт', 'Airplane'), ('Ядерная бомба', 'Nuke Bomb')], max_length=50)),
                ('weapon_range', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('weapon_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=30)),
                ('one_deck', models.IntegerField(default=4)),
                ('two_deck', models.IntegerField(default=3)),
                ('three_deck', models.IntegerField(default=2)),
                ('four_deck', models.IntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game')),
            ],
        ),
        migrations.CreateModel(
            name='MarkedCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.field')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_length', models.IntegerField()),
                ('is_dead', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.field')),
            ],
        ),
        migrations.CreateModel(
            name='ShipPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('is_damaged', models.BooleanField(default=False)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.ship')),
            ],
        ),
        migrations.CreateModel(
            name='UserWeapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.user')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_amount', models.IntegerField(default=0)),
                ('user_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.userweapons')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.weapontype')),
            ],
        ),
    ]
